name: 'Pretended Studio'
description: 'Free Open Source Software (FOSS) Studio'
author: 'Mohamad Rido'
email: 'mail@pretendedstudio.com'
permalink: /:title
plugin:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
markdown: kramdown
highlighter: rouge
paginate: 15
